Module7 task2
htmlacademy-react/1335517-six-cities-5 pull request #13
Opened 2020-11-18 12:49 UTC by potap1986

2020-11-20 15:47 UTC, devanonymous requested changes

2020-11-20 15:47 UTC, devanonymous commented on src/components/app/app.jsx
> +  // const [setActiveOffer] = React.useState(null);
Не должно быть закоментированного кода

2020-11-20 15:47 UTC, devanonymous commented on src/components/app/app.jsx
> +                // setActiveOffer(offer);
Не должно быть закоментированного кода

2020-11-20 15:47 UTC, devanonymous commented on src/components/app/app.jsx
> +          } />
используй средства автоматического форматирования кода в текстовом редакторе который ты используешь, прежде чем делать комит

2020-11-20 15:47 UTC, devanonymous commented on src/components/favorites-screen/favorites-screen.jsx
> +  const noop = () => {};
вынеси в utils

2020-11-20 15:47 UTC, devanonymous commented on src/components/favorites-screen/favorites-screen.jsx
> +                React.useMemo(() => {
хуки нельзя использовать внутри jsx. https://ru.reactjs.org/docs/hooks-rules.html

2020-11-20 15:47 UTC, devanonymous commented on src/components/offer-screen/offer-screen.jsx
> +  /* const propertyReviews = React.useMemo(() => {
Не должно быть закоментированного кода

2020-11-20 15:47 UTC, devanonymous commented on src/components/review-list/review-list.jsx
> +// import CommentsList from '../comments-list/comments-list';
Не должно быть закоментированного кода

2020-11-20 15:47 UTC, devanonymous commented on src/index.jsx
> +  // store.dispatch(ApiActionCreator.checkAuth()),
убери

2020-11-20 15:47 UTC, devanonymous commented on src/store/reducers/data/data.js
> +// import reviews from '../../../mocks/reviews';
убери

2020-11-21 15:15 UTC, devanonymous commented
не выполнен 6й пункт задания "Для гостей в правом углу шапки должна отображаться ссылка «Sign In». Для зарегистрированных пользователей (прошедших авторизацию) вместо ссылки «Sign In» отображается электронная почта зарегистрированного пользователя."

2020-11-21 15:15 UTC, devanonymous commented
9й пункт тоже не выполнен

2020-11-21 15:19 UTC, devanonymous commented
пункты 8 и 5 тоже не готовы

2020-11-23 17:57 UTC, devanonymous commented
с главной страницы переадресовывает на /login, так быть не должно, согласно ТЗ главная не является приватным адресом

2020-11-23 18:00 UTC, devanonymous commented
на главной странице если кликнуть не на картинку предложения, а на его заголовок, то не открывается страница предложения и в консоле появляется ошибка

2020-11-23 18:04 UTC, devanonymous commented
> на главной странице если кликнуть не на картинку предложения, а на его заголовок, то не открывается страница предложения и в консоле появляется ошибка

в компоненте offer-card.jsx на 52 строке ты не передаешь параметры в onOfferClick и из-за этого переход не работает

2020-11-23 18:14 UTC, devanonymous requested changes

2020-11-23 18:14 UTC, devanonymous commented on src/components/offer-list/offer-list.jsx
> +  onBookmarkClick: (id, status) => dispatch(ApiActionCreator.changeOfferStatus(id, status))
Признак того добавлено ли предложение в избранное приходит нам с сервера со списка предложений. После того как ты кликаешь по ярлычку на сервер отправляется запрос, который добавляет предложение в избранное, но список предложений в нашем приложении не обновился, по этому его нужно обновить.
Если запросить список предложений после запроса changeOfferStatus, то все будет работать `onBookmarkClick: (id, status) => {
    dispatch(ApiActionCreator.changeOfferStatus(id, status));
    dispatch(ApiActionCreator.fetchOffers());
  }`

2020-11-23 18:19 UTC, devanonymous commented
Когда кликаем по offer-card на мгновение страница "моргает" какими-то левыми данными (во время загрузки предложения с сервера)

2020-11-23 18:51 UTC, potap1986 commented on src/components/offer-list/offer-list.jsx
> +  onBookmarkClick: (id, status) => dispatch(ApiActionCreator.changeOfferStatus(id, status))
Так получается что все предложения обновляются и перерисовываются. 
Я добавил функцию чтоб в state конкретное предложение в списке объявлений изменилось:
export const updateOffers = (allOffers, newOffer) => {
  const changedItemIndex = allOffers.findIndex((item) => item.id === newOffer.id);
  allOffers[changedItemIndex].isFavorite = !allOffers[changedItemIndex].isFavorite;
  return allOffers;
};

case ActionType.UPDATE_OFFERS:
      return extend(state, {
        offers: updateOffers(state.offers, adaptOfferToClient(action.payload)),
      });

И в списке то меняется но на странице перерисовка не происходит у карточки

2020-11-23 18:53 UTC, devanonymous commented on src/components/offer-list/offer-list.jsx
> +  onBookmarkClick: (id, status) => dispatch(ApiActionCreator.changeOfferStatus(id, status))
если offer-card обернуть в React.memo, то реакт не будет перерисовывать все карточки, а перерендерит только ту, которая изменилась

2020-11-23 19:16 UTC, potap1986 commented on src/components/offer-list/offer-list.jsx
> +  onBookmarkClick: (id, status) => dispatch(ApiActionCreator.changeOfferStatus(id, status))
не совсем понял как оборачивать в memo и где это можно делать

2020-11-23 19:19 UTC, devanonymous commented on src/components/offer-card/offer-card.jsx
>    className: PropTypes.string,
export default React.memo(OfferCard);

2020-11-23 19:19 UTC, devanonymous commented on src/components/offer-list/offer-list.jsx
> +  onBookmarkClick: (id, status) => dispatch(ApiActionCreator.changeOfferStatus(id, status))
в самом последнем комментарии посмотри

2020-11-23 19:19 UTC, devanonymous commented on src/components/offer-list/offer-list.jsx
> +  onBookmarkClick: (id, status) => dispatch(ApiActionCreator.changeOfferStatus(id, status))
я уже видел у тебя в коде где-то React.memo

2020-11-24 10:24 UTC, merged